- name: install prometheus node_exporter on sentry host
  hosts: sentry
  roles:
    - { role: prometheus.prometheus.node_exporter }

- name: install git and download senty repository
  hosts: sentry
  tasks:
    - name: install git
      ansible.builtin.apt:
        pkg:
          - git
        state: latest
        update_cache: true
    - name: copy git key
      ansible.builtin.copy:
        src: git.key.pem
        dest: ~/.ssh/github
        mode: '0600'
    - name: git checkout
      ansible.builtin.git:
        repo: 'git@github.com:oxiteam/self-hosted-sentry.git'
        dest: /self-hosted-sentry
        version: master
        key_file: ~/.ssh/github
        accept_hostkey: true
- name: install docker
  hosts: sentry
  tasks:
    - name: install required system packages
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
    - name: add docker gpg apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
    - name: install docker packages
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true
    - name: install docker module for python
      ansible.builtin.pip:
        name: docker
        state: present
